---
- name: Ensure dependencies are installed
  ansible.builtin.package:
    name:
      - curl
      - ca-certificates
      - kernel-modules-extra
    state: present

- name: Disable swap for the current session
  ansible.builtin.command:
    cmd: swapoff -a
  changed_when: false

- name: Ensure that swap is disabled
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Disable selinux
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  when: kubernetes_prepare_node_disable_selinux

- name: Update sysctl to allow networking
  ansible.builtin.copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1
    dest: /etc/sysctl.d/kubernetes.conf
    mode: "0644"
  notify: Reboot system

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
